# Driver sources for the top-level Makefile.

DRIVERS_C_SRCS += \
	drivers/fabric/hid/hid_kbd.c \
	drivers/fabric/net/virtio_net_stub.c \
	drivers/fabric/net/e1000_freebsd_compat.c \
	drivers/fabric/net/e1000_net_stub.c \
	drivers/fabric/display/vga_display_stub.c \
	drivers/fabric/storage/ide_storage_stub.c

DRIVERS_C_SRCS += \
	third_party/freebsd/sys/dev/e1000/e1000_api.c \
	third_party/freebsd/sys/dev/e1000/e1000_base.c \
	third_party/freebsd/sys/dev/e1000/e1000_phy.c \
	third_party/freebsd/sys/dev/e1000/e1000_nvm.c \
	third_party/freebsd/sys/dev/e1000/e1000_mac.c \
	third_party/freebsd/sys/dev/e1000/e1000_manage.c \
	third_party/freebsd/sys/dev/e1000/e1000_mbx.c \
	third_party/freebsd/sys/dev/e1000/e1000_i210.c \
	third_party/freebsd/sys/dev/e1000/e1000_vf.c \
	third_party/freebsd/sys/dev/e1000/e1000_80003es2lan.c \
	third_party/freebsd/sys/dev/e1000/e1000_ich8lan.c \
	third_party/freebsd/sys/dev/e1000/e1000_82571.c \
	third_party/freebsd/sys/dev/e1000/e1000_82575.c \
	third_party/freebsd/sys/dev/e1000/e1000_82540.c \
	third_party/freebsd/sys/dev/e1000/e1000_82542.c \
	third_party/freebsd/sys/dev/e1000/e1000_82541.c \
	third_party/freebsd/sys/dev/e1000/e1000_82543.c
