# Driver sources for the top-level Makefile.

DRIVERS_C_SRCS += \
	drivers/fabric/hid/hid_kbd.c \
	drivers/fabric/net/virtio_net_stub.c \
	drivers/fabric/net/e1000_net_stub.c \
	drivers/fabric/display/vga_display_stub.c \
	drivers/fabric/storage/ide_storage_stub.c
