#!/usr/bin/env python3

"""
Generate Rodnix POSIX syscall headers/tables from syscalls.master.
"""

from pathlib import Path
import sys


def parse_master(path: Path):
    rows = []
    seen_num = set()
    seen_name = set()
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        # Strip inline comments before parsing
        if "#" in line:
            line = line[:line.index("#")].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) != 2:
            raise ValueError(f"{path}:{lineno}: expected '<number> <name>'")
        num_s, name = parts
        try:
            num = int(num_s, 10)
        except ValueError as exc:
            raise ValueError(f"{path}:{lineno}: invalid syscall number '{num_s}'") from exc
        if num < 0:
            raise ValueError(f"{path}:{lineno}: syscall number must be >= 0")
        if num in seen_num:
            raise ValueError(f"{path}:{lineno}: duplicate syscall number {num}")
        if name in seen_name:
            raise ValueError(f"{path}:{lineno}: duplicate syscall name '{name}'")
        seen_num.add(num)
        seen_name.add(name)
        rows.append((num, name))
    rows.sort(key=lambda it: it[0])
    return rows


def enum_name(name: str) -> str:
    return f"POSIX_SYS_{name.upper()}"


def handler_name(name: str) -> str:
    return f"posix_{name}"


def gen_sysnums_header(rows, guard):
    out = []
    out.append("/* Auto-generated by scripts/mkposixsyscalls.py. Do not edit. */")
    out.append(f"#ifndef {guard}")
    out.append(f"#define {guard}")
    out.append("")
    out.append("enum {")
    for num, name in rows:
        out.append(f"    {enum_name(name)} = {num},")
    last_num = rows[-1][0] if rows else 0
    out.append("};")
    out.append("")
    out.append(f"#define POSIX_SYS_LAST {last_num}")
    out.append("")
    out.append(f"#endif /* {guard} */")
    out.append("")
    return "\n".join(out)


def gen_sysent_inc(rows):
    out = []
    out.append("/* Auto-generated by scripts/mkposixsyscalls.py. Do not edit. */")
    out.append("#ifndef POSIX_REGISTER")
    out.append('#error "POSIX_REGISTER(num, fn) must be defined before including posix_sysent.inc"')
    out.append("#endif")
    out.append("")
    for _, name in rows:
        out.append(f"POSIX_REGISTER({enum_name(name)}, {handler_name(name)});")
    out.append("")
    return "\n".join(out)


def write_if_changed(path: Path, content: str):
    existing = None
    if path.exists():
        existing = path.read_text(encoding="utf-8")
    if existing != content:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main():
    if len(sys.argv) != 2:
        print("usage: mkposixsyscalls.py <repo_root>")
        return 1

    root = Path(sys.argv[1]).resolve()
    master = root / "kernel/posix/syscalls.master"
    rows = parse_master(master)
    if not rows:
        print(f"{master}: no syscall entries found")
        return 1

    k_hdr = root / "kernel/posix/posix_sysnums.h"
    u_hdr = root / "userland/include/posix_sysnums.h"
    inc = root / "kernel/posix/posix_sysent.inc"

    write_if_changed(k_hdr, gen_sysnums_header(rows, "_RODNIX_POSIX_SYSNUMS_H"))
    write_if_changed(u_hdr, gen_sysnums_header(rows, "_RODNIX_USERLAND_POSIX_SYSNUMS_H"))
    write_if_changed(inc, gen_sysent_inc(rows))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
